-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE invoices (
  id TEXT PRIMARY KEY,
  number TEXT NOT NULL,
  issue_date TEXT NOT NULL,
  type TEXT NOT NULL, -- 'PURCHASE' | 'SALE'
  total_amount REAL DEFAULT 0,
  discount REAL DEFAULT 0,
  status TEXT DEFAULT 'PAID', -- 'PENDING' | 'PAID' | 'CANCELLED'
  supplier_id TEXT,
  created_at INTEGER DEFAULT (strftime('%s', 'now')), items TEXT,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE movements (
  id TEXT PRIMARY KEY,
  tipo TEXT NOT NULL,
  product_id TEXT NOT NULL REFERENCES products(id),
  sku TEXT NOT NULL,
  quantidade REAL NOT NULL,
  placa TEXT,
  responsavel TEXT,
  observacao TEXT,
  data_hora INTEGER NOT NULL,
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
, product_name TEXT);

CREATE TABLE price_history (
  id TEXT PRIMARY KEY,
  product_id TEXT NOT NULL,
  price REAL NOT NULL,
  type TEXT NOT NULL, -- 'SALE' or 'COST'
  date INTEGER DEFAULT (strftime('%s', 'now')),
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE products (
  id TEXT PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  quantity INTEGER DEFAULT 0,
  min_quantity INTEGER DEFAULT 2,
  price REAL DEFAULT 0,
  image_url TEXT,
  supplier_id TEXT,
  created_at INTEGER DEFAULT (strftime('%s', 'now')), location TEXT, minimo INTEGER DEFAULT 1, unidade TEXT, local TEXT,
  FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE purchase_requests (
  id TEXT PRIMARY KEY,
  product_id TEXT,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  status TEXT DEFAULT 'PENDING',
  requester_id TEXT,
  created_at INTEGER DEFAULT (strftime('%s', 'now')),
  updated_at INTEGER DEFAULT (strftime('%s', 'now')),
  FOREIGN KEY (product_id) REFERENCES products(id),
  FOREIGN KEY (requester_id) REFERENCES es_system__auth_user(id)
);

CREATE TABLE suppliers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  contact TEXT,
  email TEXT,
  phone TEXT,
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE transactions (
  id TEXT PRIMARY KEY,
  product_id TEXT NOT NULL,
  type TEXT NOT NULL, -- 'IN' | 'OUT'
  quantity INTEGER NOT NULL,
  date TEXT NOT NULL,
  description TEXT,
  invoice_id TEXT,
  discount REAL DEFAULT 0,
  created_at INTEGER DEFAULT (strftime('%s', 'now')), unit_price REAL,
  FOREIGN KEY (product_id) REFERENCES products(id),
  FOREIGN KEY (invoice_id) REFERENCES invoices(id)
);

CREATE TABLE trucks (
  id TEXT PRIMARY KEY,
  placa TEXT NOT NULL UNIQUE,
  filial TEXT,
  tipo TEXT,
  ativo INTEGER DEFAULT 1,
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

-- INDEXS

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_trucks_placa ON trucks(placa);

CREATE INDEX invoices_number_idx ON invoices(number);

CREATE INDEX movements_product_id_idx ON movements(product_id);

CREATE INDEX movements_tipo_idx ON movements(tipo);

CREATE UNIQUE INDEX products_sku_unique_idx ON products(sku);

CREATE INDEX transactions_product_id_idx ON transactions(product_id);
