// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { suppliers, products, invoices, transactions, esSystemAuthUser, purchaseRequests, priceHistory, movements } from "./db_schema";

export const productsRelations = relations(products, ({one, many}) => ({
	supplier: one(suppliers, {
		fields: [products.supplierId],
		references: [suppliers.id]
	}),
	transactions: many(transactions),
	purchaseRequests: many(purchaseRequests),
	priceHistories: many(priceHistory),
	movements: many(movements),
}));

export const suppliersRelations = relations(suppliers, ({many}) => ({
	products: many(products),
	invoices: many(invoices),
}));

export const invoicesRelations = relations(invoices, ({one, many}) => ({
	supplier: one(suppliers, {
		fields: [invoices.supplierId],
		references: [suppliers.id]
	}),
	transactions: many(transactions),
}));

export const transactionsRelations = relations(transactions, ({one}) => ({
	invoice: one(invoices, {
		fields: [transactions.invoiceId],
		references: [invoices.id]
	}),
	product: one(products, {
		fields: [transactions.productId],
		references: [products.id]
	}),
}));

export const purchaseRequestsRelations = relations(purchaseRequests, ({one}) => ({
	esSystemAuthUser: one(esSystemAuthUser, {
		fields: [purchaseRequests.requesterId],
		references: [esSystemAuthUser.id]
	}),
	product: one(products, {
		fields: [purchaseRequests.productId],
		references: [products.id]
	}),
}));

export const esSystemAuthUserRelations = relations(esSystemAuthUser, ({many}) => ({
	purchaseRequests: many(purchaseRequests),
}));

export const priceHistoryRelations = relations(priceHistory, ({one}) => ({
	product: one(products, {
		fields: [priceHistory.productId],
		references: [products.id]
	}),
}));

export const movementsRelations = relations(movements, ({one}) => ({
	product: one(products, {
		fields: [movements.productId],
		references: [products.id]
	}),
}));