// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, foreignKey, real, index } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const suppliers = sqliteTable("suppliers", {
	id: text().primaryKey(),
	name: text().notNull(),
	contact: text(),
	email: text(),
	phone: text(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
});

export const products = sqliteTable("products", {
	id: text().primaryKey(),
	sku: text().notNull(),
	name: text().notNull(),
	category: text().notNull(),
	quantity: integer().default(0),
	minQuantity: integer("min_quantity").default(2),
	price: real(),
	imageUrl: text("image_url"),
	supplierId: text("supplier_id").references(() => suppliers.id),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	location: text(),
	minimo: integer().default(1),
	unidade: text(),
	local: text(),
},
(table) => [
	uniqueIndex("products_sku_unique_idx").on(table.sku),
]);

export const invoices = sqliteTable("invoices", {
	id: text().primaryKey(),
	number: text().notNull(),
	issueDate: text("issue_date").notNull(),
	type: text().notNull(),
	totalAmount: real("total_amount"),
	discount: real(),
	status: text().default("PAID"),
	supplierId: text("supplier_id").references(() => suppliers.id),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	items: text(),
},
(table) => [
	index("invoices_number_idx").on(table.number),
]);

export const transactions = sqliteTable("transactions", {
	id: text().primaryKey(),
	productId: text("product_id").notNull().references(() => products.id),
	type: text().notNull(),
	quantity: integer().notNull(),
	date: text().notNull(),
	description: text(),
	invoiceId: text("invoice_id").references(() => invoices.id),
	discount: real(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	unitPrice: real("unit_price"),
},
(table) => [
	index("transactions_product_id_idx").on(table.productId),
]);

export const purchaseRequests = sqliteTable("purchase_requests", {
	id: text().primaryKey(),
	productId: text("product_id").references(() => products.id),
	productName: text("product_name").notNull(),
	quantity: integer().notNull(),
	status: text().default("PENDING"),
	requesterId: text("requester_id").references(() => esSystemAuthUser.id),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	updatedAt: integer("updated_at").default(sql`(strftime('%s', 'now'))`),
});

export const priceHistory = sqliteTable("price_history", {
	id: text().primaryKey(),
	productId: text("product_id").notNull().references(() => products.id),
	price: real().notNull(),
	type: text().notNull(),
	date: integer().default(sql`(strftime('%s', 'now'))`),
});

export const movements = sqliteTable("movements", {
	id: text().primaryKey(),
	tipo: text().notNull(),
	productId: text("product_id").notNull().references(() => products.id),
	sku: text().notNull(),
	quantidade: real().notNull(),
	placa: text(),
	responsavel: text(),
	observacao: text(),
	dataHora: integer("data_hora").notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	productName: text("product_name"),
},
(table) => [
	index("movements_tipo_idx").on(table.tipo),
	index("movements_product_id_idx").on(table.productId),
]);

export const trucks = sqliteTable("trucks", {
	id: text().primaryKey(),
	placa: text().notNull(),
	filial: text(),
	tipo: text(),
	ativo: integer().default(1),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("idx_trucks_placa").on(table.placa),
]);

